# Issue templates are based on templates for poetry:
# https://github.com/python-poetry/poetry/tree/master/.github/ISSUE_TEMPLATE
blank_issues_enabled: false
contact_links:
  - name: "\U0001F381 Feature requests"
    url: https://forum.komutracker.net/c/features
    about: Request and vote on features on the forum.
  - name: "\u2753 Support"
    url: https://forum.komutracker.net/
    about: Need help with something? Ask for help on the forum!
  - name: "\U0001F4AD Discussion (on our forum)"
    url: https://forum.komutracker.net/
    about: The preferred place for general discussion about KomuTracker
  - name: "\U0001F4AD Discussion (on GitHub Discussions)"
    url: https://github.com/nccasia/komutracker/discussions
    about: We're testing it out (but the forum is still the preferred place).
  - name: "\U0001F4AC Chat with us on Discord"
    url: https://discord.gg/dctJK6USjK
    about: We love to see people who are active in issues on our Discord, come join us!
